### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by sad1502** [Topinambur223606/PixelPlanetBot#1]
Hi, have some way to traduce the bot? i already modified the archives on the bot but, the bot still english language.

**Comment by Topinambur223606** [comment]
You want bot to write logs in another language?
If I understand you correctly, you have translated log lines in source code.

Firstly, you don't need whole archive for bot to work - just single executable file.
What about translation - executable file is already compiled, it contains inside itself all lines that it writes, so just changing source code files wouldn't help. To get translated version of bot, you should compile it again by yourself with your changes included.

Hope it will help.

**Comment by sad1502** [comment]
Oh ok, thx!
